/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao Emanuel
 */
public class Telafilme04 extends javax.swing.JFrame {

    int pontos,erros;
    
    public Telafilme04() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         pontos = 0;
         erros = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblvida1 = new javax.swing.JLabel();
        lblvida2 = new javax.swing.JLabel();
        lblvida3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblpontos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txta = new javax.swing.JFormattedTextField();
        txtc = new javax.swing.JFormattedTextField();
        txti = new javax.swing.JFormattedTextField();
        txtn = new javax.swing.JFormattedTextField();
        txtc2 = new javax.swing.JFormattedTextField();
        txto = new javax.swing.JFormattedTextField();
        txtp = new javax.swing.JFormattedTextField();
        txta2 = new javax.swing.JFormattedTextField();
        txts = new javax.swing.JFormattedTextField();
        txts2 = new javax.swing.JFormattedTextField();
        txto2 = new javax.swing.JFormattedTextField();
        txts3 = new javax.swing.JFormattedTextField();
        txtd = new javax.swing.JFormattedTextField();
        txte = new javax.swing.JFormattedTextField();
        txtv = new javax.swing.JFormattedTextField();
        txto3 = new javax.swing.JFormattedTextField();
        txtc4 = new javax.swing.JFormattedTextField();
        txte2 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qual o Nome do Filme ??");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VIDAS : ");

        lblvida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        lblvida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        lblvida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PONTOS:");

        lblpontos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        lblpontos.setForeground(new java.awt.Color(255, 255, 255));
        lblpontos.setText("0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a 5 passos de você.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        try {
            txta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaKeyReleased(evt);
            }
        });

        try {
            txtc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcKeyReleased(evt);
            }
        });

        try {
            txti.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtiKeyReleased(evt);
            }
        });

        try {
            txtn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnKeyReleased(evt);
            }
        });

        try {
            txtc2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtc2KeyReleased(evt);
            }
        });

        try {
            txto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoKeyReleased(evt);
            }
        });

        try {
            txtp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpKeyReleased(evt);
            }
        });

        try {
            txta2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta2ActionPerformed(evt);
            }
        });
        txta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta2KeyReleased(evt);
            }
        });

        try {
            txts.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsKeyReleased(evt);
            }
        });

        try {
            txts2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txts2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txts2KeyReleased(evt);
            }
        });

        try {
            txto2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txto2KeyReleased(evt);
            }
        });

        try {
            txts3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txts3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txts3ActionPerformed(evt);
            }
        });
        txts3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txts3KeyReleased(evt);
            }
        });

        try {
            txtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdKeyReleased(evt);
            }
        });

        try {
            txte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteKeyReleased(evt);
            }
        });

        try {
            txtv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvKeyReleased(evt);
            }
        });

        try {
            txto3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txto3KeyReleased(evt);
            }
        });

        try {
            txtc4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtc4ActionPerformed(evt);
            }
        });
        txtc4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtc4KeyReleased(evt);
            }
        });

        try {
            txte2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txte2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvida2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvida3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvida1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(lblpontos)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtc2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txts2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txto2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txts3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txto3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtc4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txte2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvida3)
                            .addComponent(lblvida2)
                            .addComponent(lblvida1)
                            .addComponent(lblpontos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtc2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtc4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txte2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyReleased
        // Verificar se ousuario digitou a letra A
        if(txta.getText().equals("A")){

            //muda a cor de fun do da caixa
            txta.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txtc.setVisible(true);
            txtc.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txta.setBackground(Color.RED);
            txta.setText(null);
            txta.requestFocus();
        }
    }//GEN-LAST:event_txtaKeyReleased

    private void txtcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyReleased
        // Verificar se ousuario digitou a letra C
        if(txtc.getText().equals("C")){

            //muda a cor de fun do da caixa
            txtc.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txti.setVisible(true);
            txti.requestFocus();
            
             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txtc.setBackground(Color.RED);
            txtc.setText(null);
            txtc.requestFocus();
        }
    }//GEN-LAST:event_txtcKeyReleased

    private void txtiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiKeyReleased
        // Verificar se ousuario digitou a letra I
        if(txti.getText().equals("I")){

            //muda a cor de fun do da caixa
            txti.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txtn.setVisible(true);
            txtn.requestFocus();
            
             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txti.setBackground(Color.RED);
            txti.setText(null);
            txti.requestFocus();
        }
    }//GEN-LAST:event_txtiKeyReleased

    private void txtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyReleased
        // Verificar se ousuario digitou a letra N
        if(txtn.getText().equals("N")){

            //muda a cor de fun do da caixa
            txtn.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txtc2.setVisible(true);
            txtc2.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txtn.setBackground(Color.RED);
            txtn.setText(null);
            txtn.requestFocus();
        }
    }//GEN-LAST:event_txtnKeyReleased

    private void txtc2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc2KeyReleased
        // Verificar se ousuario digitou a letra C2
        if(txtc2.getText().equals("C")){

            //muda a cor de fun do da caixa
            txtc2.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txto.setVisible(true);
            txto.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txtc2.setBackground(Color.RED);
            txtc2.setText(null);
            txtc2.requestFocus();
        }
    }//GEN-LAST:event_txtc2KeyReleased

    private void txtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoKeyReleased
        // Verificar se ousuario digitou a letra O
        if(txto.getText().equals("O")){

            //muda a cor de fun do da caixa
            txto.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txtp.setVisible(true);
            txtp.requestFocus();
            
             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txto.setBackground(Color.RED);
            txto.setText(null);
            txto.requestFocus();
        }
    }//GEN-LAST:event_txtoKeyReleased

    private void txtpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpKeyReleased
        // Verificar se ousuario digitou a letra P
        if(txtp.getText().equals("P")){

            //muda a cor de fun do da caixa
            txtp.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txta2.setVisible(true);
            txta2.requestFocus();
            
             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txtp.setBackground(Color.RED);
            txtp.setText(null);
            txtp.requestFocus();
        }
    }//GEN-LAST:event_txtpKeyReleased

    private void txta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txta2ActionPerformed

    private void txta2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta2KeyReleased
        // Verificar se ousuario digitou a letra A2
        if(txta2.getText().equals("A")){

            //muda a cor de fun do da caixa
            txta2.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txts.setVisible(true);
            txts.requestFocus();
            
             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txta2.setBackground(Color.RED);
            txta2.setText(null);
            txta2.requestFocus();
        }
    }//GEN-LAST:event_txta2KeyReleased

    private void txtsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsKeyReleased
        // Verificar se ousuario digitou a letra S
        if(txts.getText().equals("S")){

            //muda a cor de fun do da caixa
            txts.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txts2.setVisible(true);
            txts2.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txts.setBackground(Color.RED);
            txts.setText(null);
            txts.requestFocus();
        }
    }//GEN-LAST:event_txtsKeyReleased

    private void txts2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txts2KeyReleased
        // Verificar se ousuario digitou a letra S2
        if(txts2.getText().equals("S")){

            //muda a cor de fun do da caixa
            txts2.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txto2.setVisible(true);
            txto2.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txts2.setBackground(Color.RED);
            txts2.setText(null);
            txts2.requestFocus();
        }
    }//GEN-LAST:event_txts2KeyReleased

    private void txto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txto2KeyReleased
        // Verificar se ousuario digitou a letra O2
        if(txto2.getText().equals("O")){

            //muda a cor de fun do da caixa
            txto2.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txts3.setVisible(true);
            txts3.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txto2.setBackground(Color.RED);
            txto2.setText(null);
            txto2.requestFocus();
        }
    }//GEN-LAST:event_txto2KeyReleased

    private void txts3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txts3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txts3ActionPerformed

    private void txts3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txts3KeyReleased
        // Verificar se ousuario digitou a letra S3
        if(txts3.getText().equals("S")){

            //muda a cor de fun do da caixa
            txts3.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txtd.setVisible(true);
            txtd.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txts3.setBackground(Color.RED);
            txts3.setText(null);
            txts3.requestFocus();
        }
    }//GEN-LAST:event_txts3KeyReleased

    private void txtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdKeyReleased
        // Verificar se ousuario digitou a letra D
        if(txtd.getText().equals("D")){

            //muda a cor de fun do da caixa
            txtd.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txte.setVisible(true);
            txte.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txtd.setBackground(Color.RED);
            txtd.setText(null);
            txtd.requestFocus();
        }
    }//GEN-LAST:event_txtdKeyReleased

    private void txteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteKeyReleased
        // Verificar se ousuario digitou a letra E
        if(txte.getText().equals("E")){

            //muda a cor de fun do da caixa
            txte.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txtv.setVisible(true);
            txtv.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txte.setBackground(Color.RED);
            txte.setText(null);
            txte.requestFocus();
        }
    }//GEN-LAST:event_txteKeyReleased

    private void txtvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvKeyReleased
        // Verificar se ousuario digitou a letra V
        if(txtv.getText().equals("V")){

            //muda a cor de fun do da caixa
            txtv.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txto3.setVisible(true);
            txto3.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txtv.setBackground(Color.RED);
            txtv.setText(null);
            txtv.requestFocus();
        }
    }//GEN-LAST:event_txtvKeyReleased

    private void txto3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txto3KeyReleased
        // Verificar se ousuario digitou a letra O3
        if(txto3.getText().equals("O")){

            //muda a cor de fun do da caixa
            txto3.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txtc4.setVisible(true);
            txtc4.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txto3.setBackground(Color.RED);
            txto3.setText(null);
            txto3.requestFocus();
        }
    }//GEN-LAST:event_txto3KeyReleased

    private void txtc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc4ActionPerformed

    private void txtc4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc4KeyReleased
        // Verificar se ousuario digitou a letra C4
        if(txtc4.getText().equals("C")){

            //muda a cor de fun do da caixa
            txtc4.setBackground(Color.GREEN);
            //exibe o segundo  campo de texto
            txte2.setVisible(true);
            txte2.requestFocus();

             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }else{
            txtc4.setBackground(Color.RED);
            txtc4.setText(null);
            txtc4.requestFocus();
        }
    }//GEN-LAST:event_txtc4KeyReleased

    private void txte2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txte2KeyReleased
        // Verificar se ousuario digitou a letra E2
        if(txte2.getText().equals("E")){

            //muda a cor de fun do da caixa
            txte2.setBackground(Color.GREEN);
            
             //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

            JOptionPane.showMessageDialog(null, "Parabénsss, você acertou o nome do filme!! :) ");

        }else{
            txte2.setBackground(Color.RED);
            txte2.setText(null);
            txte2.requestFocus();
        }
    }//GEN-LAST:event_txte2KeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Esconder os Campos de Texto
        txtc.setVisible(false);
        txti.setVisible(false);
        txtn.setVisible(false);
        txtc2.setVisible(false);
        txto.setVisible(false);
        txtp.setVisible(false);
        txta2.setVisible(false);
        txts.setVisible(false);
        txts2.setVisible(false);
        txto2.setVisible(false);
        txts3.setVisible(false);
        txtd.setVisible(false);
        txte.setVisible(false);
        txtv.setVisible(false);
        txto3.setVisible(false);
        txtc4.setVisible(false);
        txte2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telafilme04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telafilme04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telafilme04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telafilme04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telafilme04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpontos;
    private javax.swing.JLabel lblvida1;
    private javax.swing.JLabel lblvida2;
    private javax.swing.JLabel lblvida3;
    private javax.swing.JFormattedTextField txta;
    private javax.swing.JFormattedTextField txta2;
    private javax.swing.JFormattedTextField txtc;
    private javax.swing.JFormattedTextField txtc2;
    private javax.swing.JFormattedTextField txtc4;
    private javax.swing.JFormattedTextField txtd;
    private javax.swing.JFormattedTextField txte;
    private javax.swing.JFormattedTextField txte2;
    private javax.swing.JFormattedTextField txti;
    private javax.swing.JFormattedTextField txtn;
    private javax.swing.JFormattedTextField txto;
    private javax.swing.JFormattedTextField txto2;
    private javax.swing.JFormattedTextField txto3;
    private javax.swing.JFormattedTextField txtp;
    private javax.swing.JFormattedTextField txts;
    private javax.swing.JFormattedTextField txts2;
    private javax.swing.JFormattedTextField txts3;
    private javax.swing.JFormattedTextField txtv;
    // End of variables declaration//GEN-END:variables
}
