/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao Emanuel
 */
public class Telafilme01 extends javax.swing.JFrame {

    int pontos,erros;
    
    public Telafilme01() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         pontos = 0;
         erros = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblpontos = new javax.swing.JLabel();
        txtr = new javax.swing.JFormattedTextField();
        txte = new javax.swing.JFormattedTextField();
        txtk = new javax.swing.JFormattedTextField();
        txto = new javax.swing.JFormattedTextField();
        txtj = new javax.swing.JFormattedTextField();
        btnp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Joker1.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qual o Nome do Filme ??");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PONTOS:");

        lblpontos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        lblpontos.setForeground(new java.awt.Color(255, 255, 255));
        lblpontos.setText("0");

        try {
            txtr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrKeyReleased(evt);
            }
        });

        try {
            txte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteKeyReleased(evt);
            }
        });

        try {
            txtk.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkActionPerformed(evt);
            }
        });
        txtk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkKeyReleased(evt);
            }
        });

        try {
            txto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoActionPerformed(evt);
            }
        });
        txto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoKeyReleased(evt);
            }
        });

        try {
            txtj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjActionPerformed(evt);
            }
        });
        txtj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjKeyReleased(evt);
            }
        });

        btnp.setBackground(new java.awt.Color(255, 0, 0));
        btnp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnp.setText("Proximo");
        btnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(txtj, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnp)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblpontos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpontos)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtj, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnp)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrKeyReleased
        //LETRA R
        //Verificar se o usuariio digiou a letra R
        if(txtr.getText().equals("R")){

            //Muda cor de fundo da caixa de texto
            txtr.setBackground(Color.GREEN);

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
            //Botão que chama a proxima tela
            btnp.setVisible(true);

            JOptionPane.showMessageDialog(null, "Parabénsss, você acertou o nome do filme!! :)");

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtr.setBackground(Color.RED);
            txtr.setText(null);
            txtr.requestFocus();
            
            
            lblvida1.setVisible(false);
            
            
            
            
            

        }
    }//GEN-LAST:event_txtrKeyReleased

    private void txteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteKeyReleased
        //LETRA E
        //Verificar se o usuariio digiou a letra E
        if(txte.getText().equals("E")){

            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtr.setVisible(true);
            txtr.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
        }
        else{
            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.RED);
            txte.setText(null);
            txte.requestFocus();

        }

    }//GEN-LAST:event_txteKeyReleased

    private void txtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkActionPerformed

    private void txtkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkKeyReleased
        //LETRA K
        //Verificar se o usuariio digiou a letra K
        if(txtk.getText().equals("K")){

            //Muda cor de fundo da caixa de texto
            txtk.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txte.setVisible(true);
            txte.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtk.setBackground(Color.RED);
            txtk.setText(null);
            txtk.requestFocus();

        }

    }//GEN-LAST:event_txtkKeyReleased

    private void txtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoActionPerformed

    private void txtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoKeyReleased
        //LETRA O
        //Verificar se o usuariio digiou a letra O
        if(txto.getText().equals("O")){

            //Muda cor de fundo da caixa de texto
            txto.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtk.setVisible(true);
            txtk.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
        }
        else{
            //Muda cor de fundo da caixa de texto
            txto.setBackground(Color.RED);
            txto.setText(null);
            txto.requestFocus();

        }

    }//GEN-LAST:event_txtoKeyReleased

    private void txtjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjActionPerformed

    private void txtjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjKeyReleased
        //LETRA J
        //Verificar se o usuariio digiou a letra J
        if(txtj.getText().equals("J")){

            //Muda cor de fundo da caixa de texto
            txtj.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txto.setVisible(true);
            txto.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtj.setBackground(Color.RED);
            txtj.setText(null);
            txtj.requestFocus();

        }

    }//GEN-LAST:event_txtjKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Esconder os Campos de Texto
      txto.setVisible(false);
      txtk.setVisible(false);
      txte.setVisible(false);
      txtr.setVisible(false);
      btnp.setVisible(false);
      
    }//GEN-LAST:event_formWindowOpened

    private void btnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpActionPerformed
         Telafilme02 tela02 = new Telafilme02();
        tela02.setVisible(true);
    }//GEN-LAST:event_btnpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telafilme01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpontos;
    private javax.swing.JFormattedTextField txte;
    private javax.swing.JFormattedTextField txtj;
    private javax.swing.JFormattedTextField txtk;
    private javax.swing.JFormattedTextField txto;
    private javax.swing.JFormattedTextField txtr;
    // End of variables declaration//GEN-END:variables
}
