/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao Emanuel
 */
public class Telafilme10 extends javax.swing.JFrame {

    int pontos,erros;
    
    public Telafilme10() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         pontos = 0;
         erros = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblvida1 = new javax.swing.JLabel();
        lblvida2 = new javax.swing.JLabel();
        lblvida3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblpontos = new javax.swing.JLabel();
        txte2 = new javax.swing.JFormattedTextField();
        txtu = new javax.swing.JFormattedTextField();
        txti3 = new javax.swing.JFormattedTextField();
        txth = new javax.swing.JFormattedTextField();
        txts = new javax.swing.JFormattedTextField();
        txte = new javax.swing.JFormattedTextField();
        txti5 = new javax.swing.JFormattedTextField();
        txta3 = new javax.swing.JFormattedTextField();
        txtv = new javax.swing.JFormattedTextField();
        txtp = new javax.swing.JFormattedTextField();
        txta2 = new javax.swing.JFormattedTextField();
        txto = new javax.swing.JFormattedTextField();
        txtc = new javax.swing.JFormattedTextField();
        txti2 = new javax.swing.JFormattedTextField();
        txto2 = new javax.swing.JFormattedTextField();
        txtl = new javax.swing.JFormattedTextField();
        txtn = new javax.swing.JFormattedTextField();
        txta = new javax.swing.JFormattedTextField();
        txta4 = new javax.swing.JFormattedTextField();
        txtd = new javax.swing.JFormattedTextField();
        txti = new javax.swing.JFormattedTextField();
        txto3 = new javax.swing.JFormattedTextField();
        txtm2 = new javax.swing.JFormattedTextField();
        txto4 = new javax.swing.JFormattedTextField();
        txtc2 = new javax.swing.JFormattedTextField();
        txtm = new javax.swing.JFormattedTextField();
        txtr = new javax.swing.JFormattedTextField();
        txtr3 = new javax.swing.JFormattedTextField();
        txts2 = new javax.swing.JFormattedTextField();
        txtr2 = new javax.swing.JFormattedTextField();
        txtd3 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qual o Nome do Filme ??");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VIDAS : ");

        lblvida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        lblvida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        lblvida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PONTOS:");

        lblpontos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        lblpontos.setForeground(new java.awt.Color(255, 255, 255));
        lblpontos.setText("0");

        try {
            txte2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txte2KeyReleased(evt);
            }
        });

        try {
            txtu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuKeyReleased(evt);
            }
        });

        try {
            txti3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txti3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txti3KeyReleased(evt);
            }
        });

        try {
            txth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthKeyReleased(evt);
            }
        });

        try {
            txts.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsKeyReleased(evt);
            }
        });

        try {
            txte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteKeyReleased(evt);
            }
        });

        try {
            txti5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txti5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txti5KeyReleased(evt);
            }
        });

        try {
            txta3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta3KeyReleased(evt);
            }
        });

        try {
            txtv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvKeyReleased(evt);
            }
        });

        try {
            txtp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpKeyReleased(evt);
            }
        });

        try {
            txta2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta2KeyReleased(evt);
            }
        });

        try {
            txto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoKeyReleased(evt);
            }
        });

        try {
            txtc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcKeyReleased(evt);
            }
        });

        try {
            txti2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txti2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txti2KeyReleased(evt);
            }
        });

        try {
            txto2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txto2KeyReleased(evt);
            }
        });

        try {
            txtl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlKeyReleased(evt);
            }
        });

        try {
            txtn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnKeyReleased(evt);
            }
        });

        try {
            txta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaKeyReleased(evt);
            }
        });

        try {
            txta4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta4KeyReleased(evt);
            }
        });

        try {
            txtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdKeyReleased(evt);
            }
        });

        try {
            txti.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtiKeyReleased(evt);
            }
        });

        try {
            txto3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txto3KeyReleased(evt);
            }
        });

        try {
            txtm2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtm2KeyReleased(evt);
            }
        });

        try {
            txto4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txto4KeyReleased(evt);
            }
        });

        try {
            txtc2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtc2KeyReleased(evt);
            }
        });

        try {
            txtm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmKeyReleased(evt);
            }
        });

        try {
            txtr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrKeyReleased(evt);
            }
        });

        try {
            txtr3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtr3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtr3KeyReleased(evt);
            }
        });

        try {
            txts2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txts2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txts2KeyReleased(evt);
            }
        });

        try {
            txtr2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtr2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtr2KeyReleased(evt);
            }
        });

        try {
            txtd3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtd3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtd3KeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cropped-loucos-por-amor-viciadas-por-dinheiro.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblvida1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvida2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvida3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblpontos)
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txto2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txto3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtr2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtm2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtd3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txti3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txte2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txti5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtr3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txto4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtc2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txti2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txta3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txta4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txts2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21))
                    .addComponent(lblpontos)
                    .addComponent(lblvida3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20))
                    .addComponent(lblvida1)
                    .addComponent(lblvida2))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtr2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txta3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txta4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txti2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtc2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtm2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txto4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtr3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txte2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtd3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txti3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txti5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlKeyReleased
        //Verificar se o usuariio digiou a letra L
        if(txtl.getText().equals("L")){

            //Muda cor de fundo da caixa de texto
            txtl.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txto.setVisible(true);
            txto.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtl.setBackground(Color.RED);
            txtl.setText(null);
            txtl.requestFocus();

        }
    }//GEN-LAST:event_txtlKeyReleased

    private void txtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoKeyReleased
        //Verificar se o usuariio digiou a letra O
        if(txto.getText().equals("O")){

            //Muda cor de fundo da caixa de texto
            txto.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtu.setVisible(true);
            txtu.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txto.setBackground(Color.RED);
            txto.setText(null);
            txto.requestFocus();

        }
    }//GEN-LAST:event_txtoKeyReleased

    private void txtuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuKeyReleased
        //Verificar se o usuariio digiou a letra U
        if(txtu.getText().equals("U")){

            //Muda cor de fundo da caixa de texto
            txtu.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtc.setVisible(true);
            txtc.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtu.setBackground(Color.RED);
            txtu.setText(null);
            txtu.requestFocus();

        }
    }//GEN-LAST:event_txtuKeyReleased

    private void txtcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyReleased
        //Verificar se o usuariio digiou a letra C
        if(txtc.getText().equals("C")){

            //Muda cor de fundo da caixa de texto
            txtc.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txta.setVisible(true);
            txta.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtc.setBackground(Color.RED);
            txtc.setText(null);
            txtc.requestFocus();

        }
    }//GEN-LAST:event_txtcKeyReleased

    private void txtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyReleased
        //Verificar se o usuariio digiou a letra A
        if(txta.getText().equals("A")){

            //Muda cor de fundo da caixa de texto
            txta.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txts.setVisible(true);
            txts.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txta.setBackground(Color.RED);
            txta.setText(null);
            txta.requestFocus();

        }
    }//GEN-LAST:event_txtaKeyReleased

    private void txtsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsKeyReleased
        //Verificar se o usuariio digiou a letra S
        if(txts.getText().equals("S")){

            //Muda cor de fundo da caixa de texto
            txts.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtp.setVisible(true);
            txtp.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txts.setBackground(Color.RED);
            txts.setText(null);
            txts.requestFocus();

        }
    }//GEN-LAST:event_txtsKeyReleased

    private void txtpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpKeyReleased
        //Verificar se o usuariio digiou a letra P
        if(txtp.getText().equals("P")){

            //Muda cor de fundo da caixa de texto
            txtp.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txto2.setVisible(true);
            txto2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtp.setBackground(Color.RED);
            txtp.setText(null);
            txtp.requestFocus();

        }
    }//GEN-LAST:event_txtpKeyReleased

    private void txto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txto2KeyReleased
        //Verificar se o usuariio digiou a letra O2
        if(txto2.getText().equals("O")){

            //Muda cor de fundo da caixa de texto
            txto2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtr.setVisible(true);
            txtr.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txto2.setBackground(Color.RED);
            txto2.setText(null);
            txto2.requestFocus();

        }
    }//GEN-LAST:event_txto2KeyReleased

    private void txtrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrKeyReleased
        //Verificar se o usuariio digiou a letra R
        if(txtr.getText().equals("R")){

            //Muda cor de fundo da caixa de texto
            txtr.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txta2.setVisible(true);
            txta2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtr.setBackground(Color.RED);
            txtr.setText(null);
            txtr.requestFocus();

        }
    }//GEN-LAST:event_txtrKeyReleased

    private void txta2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta2KeyReleased
        //Verificar se o usuariio digiou a letra A2
        if(txta2.getText().equals("A")){

            //Muda cor de fundo da caixa de texto
            txta2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtm.setVisible(true);
            txtm.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txta2.setBackground(Color.RED);
            txta2.setText(null);
            txta2.requestFocus();

        }
    }//GEN-LAST:event_txta2KeyReleased

    private void txtmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmKeyReleased
        //Verificar se o usuariio digiou a letra M
        if(txtm.getText().equals("M")){

            //Muda cor de fundo da caixa de texto
            txtm.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txto3.setVisible(true);
            txto3.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtm.setBackground(Color.RED);
            txtm.setText(null);
            txtm.requestFocus();

        }
    }//GEN-LAST:event_txtmKeyReleased

    private void txto3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txto3KeyReleased
        //Verificar se o usuariio digiou a letra O3
        if(txto3.getText().equals("O")){

            //Muda cor de fundo da caixa de texto
            txto3.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtr2.setVisible(true);
            txtr2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txto3.setBackground(Color.RED);
            txto3.setText(null);
            txto3.requestFocus();

        }
    }//GEN-LAST:event_txto3KeyReleased

    private void txtr2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtr2KeyReleased
        //Verificar se o usuariio digiou a letra R2
        if(txtr2.getText().equals("R")){

            //Muda cor de fundo da caixa de texto
            txtr2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtv.setVisible(true);
            txtv.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtr2.setBackground(Color.RED);
            txtr2.setText(null);
            txtr2.requestFocus();

        }
    }//GEN-LAST:event_txtr2KeyReleased

    private void txtvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvKeyReleased
        //Verificar se o usuariio digiou a letra V
        if(txtv.getText().equals("V")){

            //Muda cor de fundo da caixa de texto
            txtv.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txti.setVisible(true);
            txti.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtv.setBackground(Color.RED);
            txtv.setText(null);
            txtv.requestFocus();

        }
    }//GEN-LAST:event_txtvKeyReleased

    private void txtiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiKeyReleased
        //Verificar se o usuariio digiou a letra I
        if(txti.getText().equals("I")){

            //Muda cor de fundo da caixa de texto
            txti.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtc2.setVisible(true);
            txtc2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txti.setBackground(Color.RED);
            txti.setText(null);
            txti.requestFocus();

        }
    }//GEN-LAST:event_txtiKeyReleased

    private void txtc2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc2KeyReleased
        //Verificar se o usuariio digiou a letra C2
        if(txtc2.getText().equals("C")){

            //Muda cor de fundo da caixa de texto
            txtc2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txti2.setVisible(true);
            txti2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtc2.setBackground(Color.RED);
            txtc2.setText(null);
            txtc2.requestFocus();

        }
    }//GEN-LAST:event_txtc2KeyReleased

    private void txti2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txti2KeyReleased
        //Verificar se o usuariio digiou a letra I2
        if(txti2.getText().equals("I")){

            //Muda cor de fundo da caixa de texto
            txti2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txta3.setVisible(true);
            txta3.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txti2.setBackground(Color.RED);
            txti2.setText(null);
            txti2.requestFocus();

        }
    }//GEN-LAST:event_txti2KeyReleased

    private void txta3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta3KeyReleased
        //Verificar se o usuariio digiou a letra A3
        if(txta3.getText().equals("A")){

            //Muda cor de fundo da caixa de texto
            txta3.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtd.setVisible(true);
            txtd.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txta3.setBackground(Color.RED);
            txta3.setText(null);
            txta3.requestFocus();

        }
    }//GEN-LAST:event_txta3KeyReleased

    private void txtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdKeyReleased
        //Verificar se o usuariio digiou a letra D
        if(txtd.getText().equals("D")){

            //Muda cor de fundo da caixa de texto
            txtd.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txta4.setVisible(true);
            txta4.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtd.setBackground(Color.RED);
            txtd.setText(null);
            txtd.requestFocus();

        }
    }//GEN-LAST:event_txtdKeyReleased

    private void txta4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta4KeyReleased
        //Verificar se o usuariio digiou a letra A4
        if(txta4.getText().equals("A")){

            //Muda cor de fundo da caixa de texto
            txta4.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txts2.setVisible(true);
            txts2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txta4.setBackground(Color.RED);
            txta4.setText(null);
            txta4.requestFocus();

        }
    }//GEN-LAST:event_txta4KeyReleased

    private void txts2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txts2KeyReleased
        //Verificar se o usuariio digiou a letra S2
        if(txts2.getText().equals("S")){

            //Muda cor de fundo da caixa de texto
            txts2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txte.setVisible(true);
            txte.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txts2.setBackground(Color.RED);
            txts2.setText(null);
            txts2.requestFocus();

        }
    }//GEN-LAST:event_txts2KeyReleased

    private void txteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteKeyReleased
        //Verificar se o usuariio digiou a letra E
        if(txte.getText().equals("E")){

            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtm2.setVisible(true);
            txtm2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.RED);
            txte.setText(null);
            txte.requestFocus();

        }
    }//GEN-LAST:event_txteKeyReleased

    private void txtm2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtm2KeyReleased
        //Verificar se o usuariio digiou a letra M2
        if(txtm2.getText().equals("M")){

            //Muda cor de fundo da caixa de texto
            txtm2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtd3.setVisible(true);
            txtd3.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtm2.setBackground(Color.RED);
            txtm2.setText(null);
            txtm2.requestFocus();

        }
    }//GEN-LAST:event_txtm2KeyReleased

    private void txtd3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtd3KeyReleased
        //Verificar se o usuariio digiou a letra D3
        if(txtd3.getText().equals("D")){

            //Muda cor de fundo da caixa de texto
            txtd3.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txti3.setVisible(true);
            txti3.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtd3.setBackground(Color.RED);
            txtd3.setText(null);
            txtd3.requestFocus();

        }
    }//GEN-LAST:event_txtd3KeyReleased

    private void txti3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txti3KeyReleased
        //Verificar se o usuariio digiou a letra I3
        if(txti3.getText().equals("I")){

            //Muda cor de fundo da caixa de texto
            txti3.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtn.setVisible(true);
            txtn.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txti3.setBackground(Color.RED);
            txti3.setText(null);
            txti3.requestFocus();

        }
    }//GEN-LAST:event_txti3KeyReleased

    private void txtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyReleased
        //Verificar se o usuariio digiou a letra N
        if(txtn.getText().equals("N")){

            //Muda cor de fundo da caixa de texto
            txtn.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txth.setVisible(true);
            txth.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtn.setBackground(Color.RED);
            txtn.setText(null);
            txtn.requestFocus();

        }
    }//GEN-LAST:event_txtnKeyReleased

    private void txthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthKeyReleased
        //Verificar se o usuariio digiou a letra H
        if(txth.getText().equals("H")){

            //Muda cor de fundo da caixa de texto
            txth.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txte2.setVisible(true);
            txte2.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txth.setBackground(Color.RED);
            txth.setText(null);
            txth.requestFocus();

        }
    }//GEN-LAST:event_txthKeyReleased

    private void txte2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txte2KeyReleased
        //Verificar se o usuariio digiou a letra E2
        if(txte2.getText().equals("E")){

            //Muda cor de fundo da caixa de texto
            txte2.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txti5.setVisible(true);
            txti5.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txte2.setBackground(Color.RED);
            txte2.setText(null);
            txte2.requestFocus();

        }
    }//GEN-LAST:event_txte2KeyReleased

    private void txti5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txti5KeyReleased
        //Verificar se o usuariio digiou a letra I5
        if(txti5.getText().equals("I")){

            //Muda cor de fundo da caixa de texto
            txti5.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txtr3.setVisible(true);
            txtr3.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txti5.setBackground(Color.RED);
            txti5.setText(null);
            txti5.requestFocus();

        }
    }//GEN-LAST:event_txti5KeyReleased

    private void txtr3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtr3KeyReleased
        //Verificar se o usuariio digiou a letra R3
        if(txtr3.getText().equals("R")){

            //Muda cor de fundo da caixa de texto
            txtr3.setBackground(Color.GREEN);

            //Exibe o segundo campo de texto
            txto4.setVisible(true);
            txto4.requestFocus();

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

        }
        else{
            //Muda cor de fundo da caixa de texto
            txtr3.setBackground(Color.RED);
            txtr3.setText(null);
            txtr3.requestFocus();

        }
    }//GEN-LAST:event_txtr3KeyReleased

    private void txto4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txto4KeyReleased
        //Verificar se o usuariio digiou a letra O4
        if(txto4.getText().equals("O")){

            //Muda cor de fundo da caixa de texto
            txto4.setBackground(Color.GREEN);

            //Calcula Ponto
            pontos += 10;

            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));

            JOptionPane.showMessageDialog(null, "Parabénssss, você chegou ao fim do quiz!!! ");

        }
        else{
            //Muda cor de fundo da caixa de texto
            txto4.setBackground(Color.RED);
            txto4.setText(null);
            txto4.requestFocus();

        }
    }//GEN-LAST:event_txto4KeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //Esconder os Campos de Texto
      txto.setVisible(false);
      txtu.setVisible(false);
      txtc.setVisible(false);
      txta.setVisible(false);
      txts.setVisible(false);
      txtp.setVisible(false);
      txto2.setVisible(false);
      txtr.setVisible(false);
      txta2.setVisible(false);
      txtm.setVisible(false);
      txto3.setVisible(false);
      txtr2.setVisible(false);
      txtv.setVisible(false);
      txti.setVisible(false);
      txtc2.setVisible(false);
      txti2.setVisible(false);
      txta3.setVisible(false);
      txtd.setVisible(false);
      txta4.setVisible(false);
      txts2.setVisible(false);
      txte.setVisible(false);
      txtm2.setVisible(false);
      txtd3.setVisible(false);
      txti3.setVisible(false);
      txtn.setVisible(false);
      txth.setVisible(false);
      txte2.setVisible(false);
      txti5.setVisible(false);
      txtr3.setVisible(false);
      txto4.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telafilme10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telafilme10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telafilme10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telafilme10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telafilme10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpontos;
    private javax.swing.JLabel lblvida1;
    private javax.swing.JLabel lblvida2;
    private javax.swing.JLabel lblvida3;
    private javax.swing.JFormattedTextField txta;
    private javax.swing.JFormattedTextField txta2;
    private javax.swing.JFormattedTextField txta3;
    private javax.swing.JFormattedTextField txta4;
    private javax.swing.JFormattedTextField txtc;
    private javax.swing.JFormattedTextField txtc2;
    private javax.swing.JFormattedTextField txtd;
    private javax.swing.JFormattedTextField txtd3;
    private javax.swing.JFormattedTextField txte;
    private javax.swing.JFormattedTextField txte2;
    private javax.swing.JFormattedTextField txth;
    private javax.swing.JFormattedTextField txti;
    private javax.swing.JFormattedTextField txti2;
    private javax.swing.JFormattedTextField txti3;
    private javax.swing.JFormattedTextField txti5;
    private javax.swing.JFormattedTextField txtl;
    private javax.swing.JFormattedTextField txtm;
    private javax.swing.JFormattedTextField txtm2;
    private javax.swing.JFormattedTextField txtn;
    private javax.swing.JFormattedTextField txto;
    private javax.swing.JFormattedTextField txto2;
    private javax.swing.JFormattedTextField txto3;
    private javax.swing.JFormattedTextField txto4;
    private javax.swing.JFormattedTextField txtp;
    private javax.swing.JFormattedTextField txtr;
    private javax.swing.JFormattedTextField txtr2;
    private javax.swing.JFormattedTextField txtr3;
    private javax.swing.JFormattedTextField txts;
    private javax.swing.JFormattedTextField txts2;
    private javax.swing.JFormattedTextField txtu;
    private javax.swing.JFormattedTextField txtv;
    // End of variables declaration//GEN-END:variables
}
