/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao Emanuel
 */
public class Telafilme01 extends javax.swing.JFrame {

    /**
     * Creates new form Telafilme01
     */
    public Telafilme01() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    int erros = 0;
    
    public void Erros(){
        
        erros++;
        if(erros >= 3){
        JOptionPane.showMessageDialog(null, "Atingiu 3 erros");
        dispose();
        new Teladeplay().setVisible(true);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtj = new javax.swing.JFormattedTextField();
        txto = new javax.swing.JFormattedTextField();
        txtk = new javax.swing.JFormattedTextField();
        txte = new javax.swing.JFormattedTextField();
        txtr = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("Qual o Nome do Filme ??");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Joker.jpg"))); // NOI18N

        try {
            txtj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjActionPerformed(evt);
            }
        });
        txtj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjKeyReleased(evt);
            }
        });

        try {
            txto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoKeyReleased(evt);
            }
        });

        try {
            txtk.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkKeyReleased(evt);
            }
        });

        try {
            txte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteKeyReleased(evt);
            }
        });

        try {
            txtr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(685, 685, 685)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(txtj, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtj, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      //Esconder os Campos de Texto
      txto.setVisible(false);
      txtk.setVisible(false);
      txte.setVisible(false);
      txtr.setVisible(false);

        
    }//GEN-LAST:event_formWindowOpened

    private void txtjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjKeyReleased
      //LETRA J
        //Verificar se o usuariio digiou a letra J
        if(txtj.getText().equals("J")){
            
            //Muda cor de fundo da caixa de texto
            txtj.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txto.setVisible(true);
            txto.requestFocus();
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtj.setBackground(Color.RED);
            txtj.setText(null);
            txtj.requestFocus(); 
            Erros();
        }
        
    }//GEN-LAST:event_txtjKeyReleased

    private void txtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoKeyReleased
      //LETRA O
        //Verificar se o usuariio digiou a letra O
        if(txto.getText().equals("O")){
            
            //Muda cor de fundo da caixa de texto
            txto.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtk.setVisible(true);
            txtk.requestFocus();
        }
        else{
            //Muda cor de fundo da caixa de texto
            txto.setBackground(Color.RED);
            txto.setText(null);
            txto.requestFocus(); 
            Erros();
        }
        

    }//GEN-LAST:event_txtoKeyReleased

    private void txtkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkKeyReleased
      //LETRA K
        //Verificar se o usuariio digiou a letra K
        if(txtk.getText().equals("K")){
            
            //Muda cor de fundo da caixa de texto
            txtk.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txte.setVisible(true);
            txte.requestFocus();
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtk.setBackground(Color.RED);
            txtk.setText(null);
            txtk.requestFocus(); 
            Erros();
        }
        

    }//GEN-LAST:event_txtkKeyReleased

    private void txteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteKeyReleased
      //LETRA E
        //Verificar se o usuariio digiou a letra E
        if(txte.getText().equals("E")){
            
            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtr.setVisible(true);
            txtr.requestFocus();
        }
        else{
            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.RED);
            txte.setText(null);
            txte.requestFocus(); 
            Erros();
        }
        

    }//GEN-LAST:event_txteKeyReleased

    private void txtrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrKeyReleased
      //LETRA R 
       //Verificar se o usuariio digiou a letra R
        if(txtr.getText().equals("R")){
            
            //Muda cor de fundo da caixa de texto
            txtr.setBackground(Color.GREEN);
            
            JOptionPane.showMessageDialog(null, "Parabénsss, você acertou o nome do filme!! :)");
           
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtr.setBackground(Color.RED);
            txtr.setText(null);
            txtr.requestFocus(); 
            Erros();
        } 
    }//GEN-LAST:event_txtrKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telafilme01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telafilme01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txte;
    private javax.swing.JFormattedTextField txtj;
    private javax.swing.JFormattedTextField txtk;
    private javax.swing.JFormattedTextField txto;
    private javax.swing.JFormattedTextField txtr;
    // End of variables declaration//GEN-END:variables
}
