/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao Emanuel
 */
public class Telafilme06 extends javax.swing.JFrame {

     int pontos,erros;
    
    public Telafilme06() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         pontos = 0;
         erros = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblvida1 = new javax.swing.JLabel();
        lblvida2 = new javax.swing.JLabel();
        lblvida3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblpontos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txte = new javax.swing.JFormattedTextField();
        txtm2 = new javax.swing.JFormattedTextField();
        txtu = new javax.swing.JFormattedTextField();
        txtm = new javax.swing.JFormattedTextField();
        txta3 = new javax.swing.JFormattedTextField();
        txtr = new javax.swing.JFormattedTextField();
        txtd = new javax.swing.JFormattedTextField();
        txta2 = new javax.swing.JFormattedTextField();
        txtl = new javax.swing.JFormattedTextField();
        txta = new javax.swing.JFormattedTextField();
        txts2 = new javax.swing.JFormattedTextField();
        txte2 = new javax.swing.JFormattedTextField();
        txtt = new javax.swing.JFormattedTextField();
        txti2 = new javax.swing.JFormattedTextField();
        txtl2 = new javax.swing.JFormattedTextField();
        txti = new javax.swing.JFormattedTextField();
        txtm3 = new javax.swing.JFormattedTextField();
        txts = new javax.swing.JFormattedTextField();
        btnp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qual o Nome do Filme ??");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VIDAS : ");

        lblvida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        lblvida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        lblvida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VIDAS.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PONTOS:");

        lblpontos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        lblpontos.setForeground(new java.awt.Color(255, 255, 255));
        lblpontos.setText("0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ladra.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        try {
            txte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteKeyReleased(evt);
            }
        });

        try {
            txtm2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtm2KeyReleased(evt);
            }
        });

        try {
            txtu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuKeyReleased(evt);
            }
        });

        try {
            txtm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmKeyReleased(evt);
            }
        });

        try {
            txta3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta3KeyReleased(evt);
            }
        });

        try {
            txtr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrKeyReleased(evt);
            }
        });

        try {
            txtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdKeyReleased(evt);
            }
        });

        try {
            txta2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta2KeyReleased(evt);
            }
        });

        try {
            txtl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlKeyReleased(evt);
            }
        });

        try {
            txta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaKeyReleased(evt);
            }
        });

        try {
            txts2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txts2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txts2KeyReleased(evt);
            }
        });

        try {
            txte2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txte2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txte2KeyReleased(evt);
            }
        });

        try {
            txtt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttKeyReleased(evt);
            }
        });

        try {
            txti2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txti2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txti2KeyReleased(evt);
            }
        });

        try {
            txtl2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtl2KeyReleased(evt);
            }
        });

        try {
            txti.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtiKeyReleased(evt);
            }
        });

        try {
            txtm3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtm3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtm3KeyReleased(evt);
            }
        });

        try {
            txts.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsKeyReleased(evt);
            }
        });

        btnp.setBackground(new java.awt.Color(255, 0, 0));
        btnp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnp.setText("Proximo");
        btnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvida3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblvida1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblvida2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(18, 18, 18)
                .addComponent(lblpontos)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtm2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtl2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtm3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txti2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txte2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txts2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnp)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvida1)
                            .addComponent(lblvida3)
                            .addComponent(lblvida2)
                            .addComponent(lblpontos))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtm2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txts2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txte2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txti2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtl2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtm3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnp)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuKeyReleased
        //Verificar se o usuariio digiou a letra U
        if(txtu.getText().equals("U")){
            
            //Muda cor de fundo da caixa de texto
            txtu.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtm.setVisible(true);
            txtm.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtu.setBackground(Color.RED);
            txtu.setText(null);
            txtu.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtuKeyReleased

    private void txtmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmKeyReleased
        //Verificar se o usuariio digiou a letra M
        if(txtm.getText().equals("M")){
            
            //Muda cor de fundo da caixa de texto
            txtm.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txta.setVisible(true);
            txta.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtm.setBackground(Color.RED);
            txtm.setText(null);
            txtm.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtmKeyReleased

    private void txtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyReleased
        //Verificar se o usuariio digiou a letra A
        if(txta.getText().equals("A")){
            
            //Muda cor de fundo da caixa de texto
            txta.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtl.setVisible(true);
            txtl.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txta.setBackground(Color.RED);
            txta.setText(null);
            txta.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtaKeyReleased

    private void txtlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlKeyReleased
        //Verificar se o usuariio digiou a letra L
        if(txtl.getText().equals("L")){
            
            //Muda cor de fundo da caixa de texto
            txtl.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txta2.setVisible(true);
            txta2.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtl.setBackground(Color.RED);
            txtl.setText(null);
            txtl.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtlKeyReleased

    private void txta2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta2KeyReleased
        //Verificar se o usuariio digiou a letra A2
        if(txta2.getText().equals("A")){
            
            //Muda cor de fundo da caixa de texto
            txta2.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtd.setVisible(true);
            txtd.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txta2.setBackground(Color.RED);
            txta2.setText(null);
            txta2.requestFocus();
            
            

        }
    }//GEN-LAST:event_txta2KeyReleased

    private void txtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdKeyReleased
        //Verificar se o usuariio digiou a letra D
        if(txtd.getText().equals("D")){
            
            //Muda cor de fundo da caixa de texto
            txtd.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtr.setVisible(true);
            txtr.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtd.setBackground(Color.RED);
            txtd.setText(null);
            txtd.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtdKeyReleased

    private void txtrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrKeyReleased
        //Verificar se o usuariio digiou a letra R
        if(txtr.getText().equals("R")){
            
            //Muda cor de fundo da caixa de texto
            txtr.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txta3.setVisible(true);
            txta3.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtd.setBackground(Color.RED);
            txtd.setText(null);
            txtr.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtrKeyReleased

    private void txta3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta3KeyReleased
        //Verificar se o usuariio digiou a letra A3
        if(txta3.getText().equals("A")){
            
            //Muda cor de fundo da caixa de texto
            txta3.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txts.setVisible(true);
            txts.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txta3.setBackground(Color.RED);
            txta3.setText(null);
            txta3.requestFocus();
            
            

        }
    }//GEN-LAST:event_txta3KeyReleased

    private void txtsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsKeyReleased
        //Verificar se o usuariio digiou a letra S
        if(txts.getText().equals("S")){
            
            //Muda cor de fundo da caixa de texto
            txts.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txte.setVisible(true);
            txte.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txts.setBackground(Color.RED);
            txts.setText(null);
            txts.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtsKeyReleased

    private void txteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteKeyReleased
        //Verificar se o usuariio digiou a letra E
        if(txte.getText().equals("E")){
            
            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtm2.setVisible(true);
            txtm2.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txte.setBackground(Color.RED);
            txte.setText(null);
            txte.requestFocus();
            
            

        }
    }//GEN-LAST:event_txteKeyReleased

    private void txtm2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtm2KeyReleased
        //Verificar se o usuariio digiou a letra M2
        if(txtm2.getText().equals("M")){
            
            //Muda cor de fundo da caixa de texto
            txtm2.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtl2.setVisible(true);
            txtl2.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtm2.setBackground(Color.RED);
            txtm2.setText(null);
            txtm2.requestFocus();
            
            

        }
    }//GEN-LAST:event_txtm2KeyReleased

    private void txtl2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl2KeyReleased
        //Verificar se o usuariio digiou a letra L2
        if(txtl2.getText().equals("L")){
            
            //Muda cor de fundo da caixa de texto
            txtl2.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txti.setVisible(true);
            txti.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtl2.setBackground(Color.RED);
            txtl2.setText(null);
            txtl2.requestFocus();
            
        }
    }//GEN-LAST:event_txtl2KeyReleased

    private void txtiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiKeyReleased
        //Verificar se o usuariio digiou a letra I
        if(txti.getText().equals("I")){
            
            //Muda cor de fundo da caixa de texto
            txti.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtm3.setVisible(true);
            txtm3.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txti.setBackground(Color.RED);
            txti.setText(null);
            txti.requestFocus();
            
        }
    }//GEN-LAST:event_txtiKeyReleased

    private void txtm3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtm3KeyReleased
        //Verificar se o usuariio digiou a letra M3
        if(txtm3.getText().equals("M")){
            
            //Muda cor de fundo da caixa de texto
            txtm3.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txti2.setVisible(true);
            txti2.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtm3.setBackground(Color.RED);
            txtm3.setText(null);
            txtm3.requestFocus();
            
        }
    }//GEN-LAST:event_txtm3KeyReleased

    private void txti2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txti2KeyReleased
        //Verificar se o usuariio digiou a letra I2
        if(txti2.getText().equals("I")){
            
            //Muda cor de fundo da caixa de texto
            txti2.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txtt.setVisible(true);
            txtt.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txti2.setBackground(Color.RED);
            txti2.setText(null);
            txti2.requestFocus();
            
        }
    }//GEN-LAST:event_txti2KeyReleased

    private void txttKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttKeyReleased
        //Verificar se o usuariio digiou a letra T
        if(txtt.getText().equals("T")){
            
            //Muda cor de fundo da caixa de texto
            txtt.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txte2.setVisible(true);
            txte2.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txtt.setBackground(Color.RED);
            txtt.setText(null);
            txtt.requestFocus();
            
        }
    }//GEN-LAST:event_txttKeyReleased

    private void txte2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txte2KeyReleased
        //Verificar se o usuariio digiou a letra E2
        if(txte2.getText().equals("E")){
            
            //Muda cor de fundo da caixa de texto
            txte2.setBackground(Color.GREEN);
            
            //Exibe o segundo campo de texto
            txts2.setVisible(true);
            txts2.requestFocus();
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
        }
        else{
            //Muda cor de fundo da caixa de texto
            txte2.setBackground(Color.RED);
            txte2.setText(null);
            txte2.requestFocus();
            
        }
    }//GEN-LAST:event_txte2KeyReleased

    private void txts2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txts2KeyReleased
        //Verificar se o usuariio digiou a letra S2
        if(txts2.getText().equals("S")){
            
            //Muda cor de fundo da caixa de texto
            txts2.setBackground(Color.GREEN);
            
            //Calcula Ponto
            pontos += 10;
            
            //Mostra os pontos
            lblpontos.setText(String.valueOf(pontos));
            
            //Botão que chama a proxima tela
            btnp.setVisible(true);
            
            JOptionPane.showMessageDialog(null, "Parabénsss, você acertou o nome do filme!! :)");
           
        }
        else{
            //Muda cor de fundo da caixa de texto
            txts2.setBackground(Color.RED);
            txts2.setText(null);
            txts2.requestFocus();
            

            
        }
    }//GEN-LAST:event_txts2KeyReleased

    private void btnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpActionPerformed
        Telafilme07 tela07 = new Telafilme07();
        tela07.setVisible(true);
    }//GEN-LAST:event_btnpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telafilme06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telafilme06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telafilme06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telafilme06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telafilme06().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpontos;
    private javax.swing.JLabel lblvida1;
    private javax.swing.JLabel lblvida2;
    private javax.swing.JLabel lblvida3;
    private javax.swing.JFormattedTextField txta;
    private javax.swing.JFormattedTextField txta2;
    private javax.swing.JFormattedTextField txta3;
    private javax.swing.JFormattedTextField txtd;
    private javax.swing.JFormattedTextField txte;
    private javax.swing.JFormattedTextField txte2;
    private javax.swing.JFormattedTextField txti;
    private javax.swing.JFormattedTextField txti2;
    private javax.swing.JFormattedTextField txtl;
    private javax.swing.JFormattedTextField txtl2;
    private javax.swing.JFormattedTextField txtm;
    private javax.swing.JFormattedTextField txtm2;
    private javax.swing.JFormattedTextField txtm3;
    private javax.swing.JFormattedTextField txtr;
    private javax.swing.JFormattedTextField txts;
    private javax.swing.JFormattedTextField txts2;
    private javax.swing.JFormattedTextField txtt;
    private javax.swing.JFormattedTextField txtu;
    // End of variables declaration//GEN-END:variables
}
